DATA:
  common:
    dataset_name: SoccerNet
    data_root: /home/vorajv/dataset/BAS
    classes:
      - PASS
      - DRIVE
      - HEADER
      - HIGH PASS
      - OUT
      - CROSS
      - THROW IN
      - SHOT
      - BALL PLAYER BLOCK
      - PLAYER SUCCESSFUL TACKLE
      - FREE KICK
      - GOAL
    splits:
      train:
        type: VideoGameWithOpencv
        annotation_path: ${DATA.common.data_root}/train/annotations-2024-224p-train.json
        source_path: ${DATA.common.data_root}/train/
        output_map: [data, label]
        dataloader:
          batch_size: 8
          shuffle: true
          num_workers: 4
          pin_memory: true
          prefetch_factor: 1
      valid:
        type: VideoGameWithOpencv
        annotation_path: ${DATA.common.data_root}/valid/annotations-2024-224p-valid.json
        source_path: ${DATA.common.data_root}/valid/
        output_map: [data, label]
        dataloader:
          batch_size: 8
          shuffle: false
          num_workers: 4
          pin_memory: true
          prefetch_factor: 1
      valid_data_frames:
        type: VideoGameWithOpencvVideo
        annotation_path: ${DATA.common.splits.valid.annotation_path}
        source_path: ${DATA.common.splits.valid.source_path}
        output_map: [data, label]
        overlap_len: 0
        dataloader:
          batch_size: 8
          shuffle: false
          num_workers: 4
          pin_memory: true
          prefetch_factor: 1
      test:
        type: VideoGameWithOpencvVideo
        annotation_path: ${DATA.common.data_root}/test/annotations-2024-224p-test.json
        source_path: ${DATA.common.data_root}/test/
        output_map: [data, label]
        results: results_spotting_test
        metric: tight
        nms_window: 2
        overlap_len: 50
        dataloader:
          batch_size: 8
          shuffle: false
          num_workers: 4
          pin_memory: true
      challenge:
        type: VideoGameWithOpencvVideo
        annotation_path: ${DATA.common.data_root}/challenge/annotations.json
        output_map: [data, label]
        overlap_len: 50
        dataloader:
          batch_size: 4
          shuffle: false
  inputs:
    video:
      sampling:
        epoch_num_frames: 500000
        clip_len: 100
        input_fps: 25
        extract_fps: 2
      transform:
        resize:
          height: 224
          width: 398
        normalization:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      params:
        crop_dim: -1
        mixup: true
        dilate_len: 0

MODEL:
  metadata:
    family: E2E
    runner:
      type: runner_e2e
  components:
    video_encoder:
      source:
        provider: opensportslib
        registry: backbone
        name: rny008_gsm
    task_head:
      source:
        provider: opensportslib
        registry: head
        name: gru

TRAIN:
  epochs: 10
  optimizer:
    type: AdamWithScaler
    lr: 0.01
  scheduler:
    type: ChainedSchedulerE2E
    acc_grad_iter: 1
    num_epochs: ${TRAIN.epochs}
    warm_up_epochs: 3
