TASK: localization
VERSION: 2

SYSTEM:
  paths:
    log_dir: ./logs
    save_dir: ./checkpoints
    work_dir: ${SYSTEM.paths.save_dir}
  device: cuda
  gpu:
    count: 4
    id: 0
  reproducibility:
    use_seed: true
    seed: 42

DATA:
  common:
    dataset_name: SoccerNet
    data_dir: /home/vorajv/opensportslib/SoccerNet/
    classes:
      - Penalty
      - Kick-off
      - Goal
      - Substitution
      - Offside
      - Shots on target
      - Shots off target
      - Clearance
      - Ball out of play
      - Throw-in
      - Foul
      - Indirect free-kick
      - Direct free-kick
      - Corner
      - Yellow card
      - Red card
      - Yellow->red card
    runtime:
      loader_backend: opencv
    splits:
      train:
        type: FeatureClipsfromJSON
        annotation_path: ${DATA.common.data_dir}/annotations-2024-224p-train.json
        source_path: ${DATA.common.data_dir}
        output_map: [data, label]
        dataloader:
          batch_size: 256
          shuffle: true
          num_workers: 4
          pin_memory: true
      valid:
        type: FeatureClipsfromJSON
        annotation_path: ${DATA.common.data_dir}/annotations-2024-224p-valid.json
        source_path: ${DATA.common.data_dir}
        output_map: [data, label]
        dataloader:
          batch_size: 256
          shuffle: true
          num_workers: 4
          pin_memory: true
      test:
        type: FeatureVideosfromJSON
        annotation_path: ${DATA.common.data_dir}/annotations-2024-224p-test.json
        source_path: ${DATA.common.data_dir}
        output_map: [data, label]
        results: results_spotting_test_netvlad++_resnetpca512
        metric: loose
        dataloader:
          batch_size: 1
          shuffle: false
          num_workers: 1
          pin_memory: true

  inputs:
    - modality: video
      representation: features
      source:
        format: npy
      sampling:
        framerate: 2
      params:
        window_size: 20

MODEL:
  family: learnable_pooling
  runner:
    type: runner_JSON
  streams:
    video_features:
      enabled: true
      backbone:
        type: PreExtactedFeatures
        encoder: ResNET_TF2_PCA512
        feature_dim: 512
        output_dim: 512
        framerate: 2
        window_size: 20
      neck:
        type: NetVLAD++
        input_dim: 512
        output_dim: 32768
        vocab_size: 64
      preprocessor: {}
  fusion:
    type: none
    params: {}
  head:
    type: LinearLayer
    input_dim: 32768
    num_classes: 17
  post_proc:
    type: NMS
    NMS_window: 30
    NMS_threshold: 0.0
  training:
    load_weights: null

TRAIN:
  trainer:
    type: trainer_pooling
  epochs: 200
  criterion:
    type: NLLLoss
  optimizer:
    type: Adam
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0
    amsgrad: false
  scheduler:
    type: ReduceLROnPlateau
    mode: min
    factor: 1e-03
    min_lr: 1e-06
    patience: 10
    verbose: true
  execution:
    enabled: true
    evaluation_frequency: 200
  selection:
    monitor: valid_loss
    mode: min
