TASK: classification

DATA:
  dataset_name: sngar
  data_modality: tracking_parquet
  data_dir: /home/karkid/temporal-localization/data/tracking_dataset
  preload_data: false
  annotations:
    train: /home/karkid/temporal-localization/data/tracking_dataset/train/train.json
    valid: /home/karkid/temporal-localization/data/tracking_dataset/valid/valid.json
    test: /home/karkid/temporal-localization/data/tracking_dataset/test/test.json
  num_frames: 16
  frame_interval: 9
  augmentations:
    vertical_flip: true
    horizontal_flip: true
    team_flip: true
  normalize: true
  num_workers: 20
  train_batch_size: 32
  valid_batch_size: 32

MODEL:
  type: custom
  backbone:
    type: graph_conv
    encoder: gin
    hidden_dim: 64
    num_layers: 20
    dropout: 0.1
  neck:
    type: TemporalAggregation
    agr_type: attention
    hidden_dim: 64
    dropout: 0.1
  head:
    type: TrackingClassifier
    hidden_dim: 64
    dropout: 0.1
    num_classes: 10
  edge: positional
  k: 8

TRAIN:
  enabled: true
  use_weighted_sampler: true
  use_weighted_loss: false
  samples_per_class: 4000
  epochs: 2
  patience: 10
  save_every: 20

  optimizer:
    type: Adam
    lr: 0.001

  scheduler:
    type: ReduceLROnPlateau
    mode: min
    patience: 10
    factor: 0.1
    min_lr: 1e-8
  
  criterion:
    type: CrossEntropyLoss

  save_dir: ./checkpoints_tracking

SYSTEM:
  log_dir: ./logs
  seed: 42
  device: cuda
  gpu_id: 0